language: node_js
node_js:
  - "4"
  - "6"
  - "8"
before_script:
  - npm install -g istanbul coveralls
  - npm install -g mocha
  - npm install -g codeclimate-test-reporter
  - npm install

after_success:

script:
  - npm test